package com.qinhu.oneschool.DB;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table FRIEND.
 */
public class Friend_list {

    private String displayName;//备注

    private String phoneNumber;//账号
    private String timestamp;//成为好友时间
    private String letters;//首字母

    private String name;//名字；
    private String iconuri;//头像

    public String getDisplayName() {
        return displayName;
    }

    public void setDisplayName(String displayName) {
        this.displayName = displayName;
    }

    public String getPhoneNumber() {
        return phoneNumber;
    }

    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }

    public String getTimestamp() {
        return timestamp;
    }

    public void setTimestamp(String timestamp) {
        this.timestamp = timestamp;
    }

    public String getLetters() {
        return letters;
    }

    public void setLetters(String letters) {
        this.letters = letters;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getIconuri() {
        return iconuri;
    }

    public void setIconuri(String iconuri) {
        this.iconuri = iconuri;
    }

    public boolean isExitsDisplayName(){
        return !(displayName==null||displayName.equals(""));
    }
    public boolean isExitsName(){
        return !(name==null||name.equals(""));
    }
}
